This pattern of overlapping subproblems is known as dynamic programming

Write a function 'fib(n)' that takes in a number as an argument. The function should return the n-th number of the Fibonacci sequence. 

fib(n) = 1, 1, 2, 3, 5, 8, 13, 21, 34

In [1]:
def fib(n):
    if n <=2:
        return 1
    return fib(n-1) + fib(n-2)

In [2]:
fib(7)

13

In [3]:
def fib2(n, memo = {}):
    if n in memo:
        return memo[n]
    if (n<=2):
        return 1
    memo[n] = fib2(n-1, memo) + fib2(n-2, memo)
    
    return memo[n]

In [4]:
fib2(8)

21

n&nbsp;  &nbsp; &nbsp; &nbsp; : 0,  1,  2,  3,  4,  5,  6,  7, &nbsp; 8, &nbsp; 9, ... <br>
fib (n)  : 0,  1,  1,  2,  3,  5,  8,  13, 21, 34, .. 

In [5]:
import numpy as np 

In [6]:
arr = np.zeros(7)
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr = np.zeros(7, dtype=np.int8)
arr[1] =1
arr

array([0, 1, 0, 0, 0, 0, 0], dtype=int8)

In [8]:
for i,j in enumerate(arr):
    print(i, j)

0 0
1 1
2 0
3 0
4 0
5 0
6 0


In [9]:
for i in arr:
    print(i)

0
1
0
0
0
0
0


In [10]:
len(arr)

7

In [11]:
def fibt(n):
    arr = np.zeros(n+1, dtype=np.int64)
    arr[1] = 1
    
    for i in range(len(arr)):
        if i+1 < len(arr):
            arr[i+1] += arr[i]
        if i+2 < len(arr):
            arr[i+2] += arr[i]
        
    return arr[n]


In [12]:
fib(8)

21

In [13]:
fibt(50)

12586269025

Say that you are a traveller on a 2D grid. You begin in the top - left corner and your goal is to travel to the bottom - right corner. you may only move down or right.

In how many ways can you travel to the goal on the grid with dimensions m*n ?

Write a function 'gridTraveler(m,n)' that calculates this.

In [14]:
def gridTraveler_re(m,n):
    if (m,n) == (1,1):
        return 1
    if m == 0 or n == 0:
        return 0
    return gridTraveler_re(m-1,n) + gridTraveler_re(m,n-1)

In [15]:
gridTraveler_re(1,1), gridTraveler_re(2,3), gridTraveler_re(3,2), gridTraveler_re(3,3)

(1, 3, 3, 6)

O(2 ^ (n+m)) -- Time <br>
O(n+m) -------- Space

In [16]:
def gridTraveler_me(m, n, memo = {}):
    if (m,n) == (1,1):
        return 1
    if m == 0 or n == 0:
        return 0
    
    index  = str(m) +','+ str(n)
    index2 = str(n) +','+ str(m)
    
    if (index in memo):
        return memo[index]
    
    if (index2 in memo):
        return memo[index2]
    
    memo[index] = gridTraveler_me(m-1,n, memo) + gridTraveler_me(m,n-1, memo)
    
    return memo[index]

In [17]:
gridTraveler_me(1,1), gridTraveler_me(2,3), gridTraveler_me(3,2), gridTraveler_me(3,3)

(1, 3, 3, 6)

O(m*n) --- Time <br>
O(n+m) -- Space

In [18]:
empty_arr = np.empty(6)
print(empty_arr)
empty_arr[2]

[0. 0. 0. 0. 0. 0.]


0.0

In [19]:
empty_arr = np.empty((6,8))
print(empty_arr)
empty_arr[2,5]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


0.0

In [20]:
def gridTravelert(m,n):
    table = np.zeros((m+1,n+1), dtype = np.int64)
    table[1,1] = 1
    
    for i in range(n+1):
        for j in range(m+1):
            if i+1 < n+1:
                table[i+1, j] += table[i, j]

            if j+1 < m+1:
                table[i, j+1] += table[i, j]
            
    return table[m,n]
    

O(mn) -- Time <br>
O(mn) -- Space

In [21]:
gridTravelert(3,3)

6

In [22]:
gridTravelert(18,18)

2333606220

Write a function 'canSum(targetSum, numbers)' that takes in a targetSum and an array of numbers as arguments. 

The function should return a boolean indicating whether or not it is possible to generate the targetSum using numbers from the array. 

You may use an element of the array as many times as needed.

You may assume that all input numbers are non-negative.

In [23]:
def canSum_re(targetSum, numbers):
    if targetSum < 0:
        return False
    
    if targetSum == 0:
        return True
    
    for num in numbers:
        if canSum_re(targetSum - num, numbers):
            return True
    
    return False

In [24]:
canSum_re(5, [7,3,2]), canSum_re(7, [5,3,4,7]) , canSum_re(7, [2,4]) 

(True, True, False)

m = targetSum <br>
n = array length 

O(n^m) -- Time <br>
O(m) ----- Space

In [62]:
def canSum_me(targetSum, numbers, memo={}):

    if targetSum < 0:
        return False
    
    if targetSum in memo:
        return memo[targetSum]
    
    if targetSum == 0:
        return True
    
    for num in numbers:
        memo[targetSum-num] = canSum_me((targetSum-num), numbers, memo)
        if (memo[targetSum-num]):
            return True
    
    memo[targetSum] = False
            
    return False

In [63]:
canSum_me(5, [7,3,2]), canSum_me(7, [5,3,4,7]), canSum_me(7, [2,4])

(True, True, False)

m = target sum <br>
n = array length 

O(m*n) -- Time <br>
O(m) ----- Space

In [64]:
arr = np.empty(6, dtype = bool)
print(arr)
arr.fill(True)
print(arr)

[False False False False False False]
[ True  True  True  True  True  True]


In [65]:
def canSumt(targetSum, numbers):
    
    table = np.empty(targetSum+1, dtype = bool)
    table.fill(False)
    table[0] = True
    
    for i in range(targetSum):
        if table[i] == False:
            continue
        for num in numbers:
            if (i+num <= targetSum):
                table[i+num] = True
    
    return table[targetSum]

O(mn) -- Time <br>
O  ( m) -- Space

In [66]:
canSumt(5, [7,3,4])

False

Write a function `**'howSum( targetSum, numbers )'**` that takes in a targetSum and an array of numbers as arguments. 

The function should return an array containing any cobination of elements that add up to excatly the targetSum. 

If there is no combination that adds up to the targetSum, then return null. 

If there are multiple combinations possible, you may return any single one.

In [115]:
def howSum_re(targetSum, numbers):
    if targetSum < 0:
        return None
    
    if targetSum == 0:
        return []
    
    for num in numbers:
        val = howSum_re(targetSum-num, numbers)
        if val != None:
            val.append(num)
            return val
    
    return None

In [107]:
howSum_re(7, [2,3]), howSum_re(7, [5,3,4,7]), howSum_re(7, [2,4]), howSum_re(8, [5,3,2])

([3, 2, 2], [4, 3], None, [3, 5])

m = targetSum <br>
n = numbers.length

O(n^m*m) -- Time <br>
O(m) -------- Space

In [116]:
def howSum_me(targetSum, numbers, memo ={}):
    if targetSum < 0:
        return None
    
    if targetSum == 0:
        return []
    
    if targetSum in memo:
        return memo[targetSum]
    
    for num in numbers:
        memo[targetSum-num] = howSum_me(targetSum-num, numbers, memo)
        if memo[targetSum-num] != None:
            a = list(memo[targetSum-num])
            a.append(num)
            return a
    
    memo[targetSum] = None
    return None
    

In [117]:
howSum_me(7, [2,3], memo ={}), howSum_me(7, [5,3,4,7], memo ={}), howSum_me(7, [2,4], memo ={}), howSum_me(8, [5,3,2], memo ={})

([3, 2, 2], [4, 3], None, [3, 5])

O(n * m * m) -- Time <br>
O(m * m) ------ Space

In [67]:
arr = np.empty(7, dtype = 'object')

In [68]:
arr[1] = []

In [69]:
arr[0]==None

True

In [70]:
arr[5] = arr[1][:].append(4)
arr[1], arr[5]

([], None)

In [71]:
arr[5] = list(arr[1])
arr[6] = arr[1][:]
arr[6].append(5)
arr[5].append(3)
arr[1], arr[5], arr[6]

([], [3], [5])

Both the above methods have a time complexity of O(n)

In [72]:
arr

array([None, list([]), None, None, None, list([3]), list([5])],
      dtype=object)

In [73]:
def howSumt(targetSum, numbers):
    
    table = np.empty(targetSum+1, dtype = object)
    table[0] = []
    
    for i in range(targetSum):
        if table[i] == None:
            continue
        for num in numbers:
            if (i+num <= targetSum):
                table[i+num] = list(table[i])
                table[i+num].append(num)
    
    return table[targetSum]

m = targetSum <br>
n = len(numbers) 

O(m*n*m) = O(m2*n)  -- Time Complexity <br>
O(m*m) = O(m2) -- Space Complexity

In [213]:
howSumt(7, [5,3,4])

[4, 3]

Write a function 'bestSum(targetSum, numbers)' that takes in a targetSum and an array of numbers as arguments. 

The function should return an array containing the shortest combination of numbers that add up to exactly the targetSum. 

If there is a tie for the shortest combination, you may return any one of the shortest.

In [ ]:
def bestSum_re(targetSum, numbers):
    if targetSum < 0:
        return None
    
    if targetSum == 0:
        return []
    
    for num in numbers:
        val = bestSum_re(targetSum-num, numbers)
        if val != None:
            if val
            val.append(num)
            return val
    
    return None

In [234]:
table = np.empty(5, dtype = object)
table[0] = []

In [235]:
len(table[3])

TypeError: object of type 'NoneType' has no len()

In [223]:
if (table[0] is None) or (len(table[0])==0):
    print("yes")

yes


In [228]:
def bestSumt(targetSum, numbers):
    
    table = np.empty(targetSum+1, dtype = object)
    table[0] = []
    
    for i in range(targetSum):
        if table[i] == None:
            continue
        for num in numbers:
            if (i+num <= targetSum) and \
            ((table[i+num] is None) or (len(table[i+num])>len(table[i]))):
                table[i+num] = list(table[i])
                table[i+num].append(num)
    
    return table[targetSum]

In [232]:
bestSumt(12, [6,3,4])

[6, 6]

In [233]:
bestSumt(8, [2,3,5])

[5, 3]

m = targetSum <br>
n = numbers.length

O(m^2*n) -- time <br>
O(m^2) ---- Space